<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sun, 31 Dec 2023 03:43:55 +0000
 */
$conf['title'] = 'testing grounds';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-sa';
$conf['disableactions'] = 'register';
